[theme]
name = "gruvbox-dark"
[theme.overrides]
alternating_tint_bg = "#14100e"

[icons]
name = "awesome"
[icons.overrides]
memory_mem = "ğŸ§ "
backlight_empty = "â–ªï¸"
backlight_partial1 = "âš«"
backlight_partial2 = "ğŸ”…"
backlight_partial3 = "ğŸ”†"
backlight_full = "â˜€ï¸"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}@{frequency}GHz"

[[block]]
block = "time"
interval = 1
format = "%y/%d/%m %a %T"
