[theme]
name = "gruvbox-dark"
[theme.overrides]
alternating_tint_bg = "#14100e"

[icons]
name = "awesome"
[icons.overrides]
backlight_empty = "☀️"
backlight_partial1 = "☀️"
backlight_partial2 = "☀️"
backlight_partial3 = "☀️"
backlight_full = "☀️"

[[block]]
block = "sound"

[[block]]
block = "backlight"

#[[block]]
#block = "battery"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"#@{frequency}GHz"

[[block]]
block = "time"
interval = 1
format = "%y/%d/%m %a %T"
